# This workflow will install Python dependencies and run tests with several versions of Python on MacOS, Ubuntu and Windows
# When successful, packages are published to test.pypi.org and pypi.org (releases only)
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Build

env:
  PYTHON_VERSION: 3.9
  POETRY_VERSION: 1.1.12

on:
  push:
    branches: [master]
    tags: ["*"]
  pull_request:
    branches: [master]

jobs:
  test:
    name: Build wheel (${{ matrix.python-version }} on ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        python-version: [3.6, 3.7, 3.8, 3.9, "3.10", 3.11-dev]
        # exclude:
          # Python 3.11-dev on Windows is excluded for now as this combination:
          # - has no pywin32 wheel available yet, see https://github.com/mhammond/pywin32/issues/1588 and https://pypi.org/project/pywin32/301/#files
        # - has no lxml wheel available yet, and building lxml 4.6.3 fails, even with Cython 0.29.24 installed
        # - os: windows-latest
        #   python-version: "3.11-dev"

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install libkrb5-dev
        run: sudo apt-get -y install libkrb5-dev
        if: matrix.os == 'ubuntu-latest'

      - name: Install poetry ${{ env.POETRY_VERSION }}
        run: |
          pip install poetry==${{ env.POETRY_VERSION }}

      - name: Install aws-adfs and its dependencies
        run: |
          poetry install

      - name: Test with pytest
        run: |
          poetry run pytest

  publish:
    name: Publish source and wheel archives
    needs: test
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags') # Only publish tagged releases
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install poetry ${{ env.POETRY_VERSION }}
        run: |
          pip install poetry==${{ env.POETRY_VERSION }}

      - name: Build source and wheel archives
        run: |
          poetry build

      - name: Publish package to TestPyPI
        env:
          POETRY_PYPI_TOKEN_TESTPYPI: ${{ secrets.test_pypi_password }}
        run: |
          poetry config repositories.testpypi https://test.pypi.org/legacy/
          poetry publish --repository testpypi

      - name: Check Version
        id: check-version
        run: |
          [[ "$(poetry version --short)" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]] \
            || echo ::set-output name=prerelease::true

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "dist/*"
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: false
          generateReleaseNotes: true
          prerelease: ${{ steps.check-version.outputs.prerelease == 'true' }}

      - name: Publish to PyPI
        env:
          POETRY_PYPI_TOKEN_PYPI: ${{ secrets.pypi_password }}
        run: poetry publish
        # if: steps.check-version.outputs.prerelease != 'true' # Only publish final releases to PyPI
